import type { KnowledgeEntry } from "./types";

export const knowledgeBase: KnowledgeEntry[] = [
  {
    id: "about-agency",
    title: "About Maroc 360 Agency",
    category: "about",
    tags: ["about", "company", "maroc", "morocco", "agency", "who", "team"],
    keywords: [
      "who",
      "what",
      "maroc",
      "morocco",
      "agency",
      "company",
      "about",
      "story",
      "mission",
      "team",
      "located",
      "based",
      "where",
    ],
    answer:
      "Maroc 360 Agency is a full-service digital marketing agency based in Morocco. We help Moroccan brands grow with strategy, creative, paid media, SEO, social, and content that delivers measurable results. Our name says it all: a 360° view of marketing for Moroccan businesses ready to grow and shine.",
    followUps: ["Where are you located?", "What services do you offer?", "How do I get started?"],
  },
  {
    id: "services-overview",
    title: "Services overview",
    category: "services",
    tags: ["services", "what", "offer", "do"],
    keywords: [
      "service",
      "services",
      "offer",
      "offering",
      "what",
      "do",
      "you",
      "provide",
      "help",
      "capabilities",
    ],
    answer:
      "We cover the full 360° of digital marketing: strategy and planning, paid media (Meta, Google, TikTok, LinkedIn), SEO and content, social media management, performance tracking, and creative production. We also build marketing platforms and dashboards so you can see exactly what is working in real time.",
    followUps: ["Tell me about paid media", "What is included in SEO & content?", "Do you build dashboards?"],
  },
  {
    id: "service-strategy",
    title: "Strategy & Planning",
    category: "services",
    tags: ["strategy", "planning", "consulting"],
    keywords: ["strategy", "planning", "consulting", "audit", "roadmap", "plan", "go-to-market"],
    answer:
      "Our strategy engagements usually start with a marketing audit and a clear growth roadmap: positioning, audience, channel mix, budget allocation, and a 90-day execution plan. We work side-by-side with founders and marketing leads to make sure the strategy is something the team can actually run with.",
    followUps: ["How long does a strategy engagement take?", "What does a strategy engagement cost?"],
  },
  {
    id: "service-paid-media",
    title: "Paid Media",
    category: "services",
    tags: ["paid", "media", "ads", "ppc", "meta", "google", "tiktok", "linkedin"],
    keywords: [
      "paid",
      "media",
      "ads",
      "advertising",
      "ppc",
      "meta",
      "facebook",
      "instagram",
      "google",
      "ads",
      "tiktok",
      "linkedin",
      "campaigns",
    ],
    answer:
      "We run paid campaigns across Meta (Facebook & Instagram), Google Ads, TikTok, and LinkedIn, with a strong focus on Moroccan and MENA audiences. Every campaign starts with clear KPIs, a tested creative pipeline, and weekly performance reviews so we can iterate fast and scale what works.",
    followUps: ["Which platform is best for me?", "What budget do I need for paid ads?"],
  },
  {
    id: "service-seo-content",
    title: "SEO & Content",
    category: "services",
    tags: ["seo", "content", "writing", "blog", "organic"],
    keywords: [
      "seo",
      "search",
      "content",
      "blog",
      "writing",
      "organic",
      "google",
      "ranking",
      "keywords",
      "articles",
    ],
    answer:
      "We handle the full SEO and content loop: technical SEO audit, keyword research, on-page optimization, and a content calendar of articles, landing pages, and social posts written for Moroccan and French-speaking audiences. The goal is simple: more qualified traffic that converts.",
    followUps: ["How long until SEO pays off?", "Do you write in Arabic, French, and English?"],
  },
  {
    id: "service-social",
    title: "Social Media",
    category: "services",
    tags: ["social", "instagram", "facebook", "tiktok", "community"],
    keywords: ["social", "instagram", "facebook", "tiktok", "community", "management", "posts", "reels"],
    answer:
      "We manage social media end-to-end: content strategy, monthly calendars, design, copywriting, publishing, and community management. We focus on Reels and short-form video because that is where Moroccan audiences spend their time, and we keep a close eye on what actually drives engagement and sales.",
    followUps: ["Do you produce video content?", "How often do you post?"],
  },
  {
    id: "service-platform",
    title: "Marketing Platform",
    category: "services",
    tags: ["platform", "dashboard", "tracking", "analytics", "attribution"],
    keywords: ["platform", "dashboard", "tracking", "attribution", "analytics", "reporting", "bi"],
    answer:
      "We build custom marketing dashboards that pull data from your ad accounts, your CRM, and your website into one place. No more spreadsheets: you see spend, leads, revenue, and ROI in real time, and you know exactly where to double down.",
    followUps: ["Which tools do you integrate with?", "Can I keep my current analytics stack?"],
  },
  {
    id: "service-creative",
    title: "Creative Studio",
    category: "services",
    tags: ["creative", "design", "video", "branding"],
    keywords: ["creative", "design", "video", "production", "branding", "logo", "visuals", "photo"],
    answer:
      "Our creative studio produces ad creatives, social content, landing pages, brand identity, and short-form video. Everything is designed to perform, not just to look good: we test hooks, formats, and visuals based on what the data tells us.",
    followUps: ["Do you do branding?", "How fast can you turn around a campaign?"],
  },
  {
    id: "industries",
    title: "Industries we serve",
    category: "industries",
    tags: ["industries", "sector", "ecommerce", "hospitality", "real estate", "services"],
    keywords: [
      "industry",
      "industries",
      "sector",
      "ecommerce",
      "e-commerce",
      "hospitality",
      "travel",
      "hotel",
      "real",
      "estate",
      "professional",
      "services",
      "b2b",
      "b2c",
    ],
    answer:
      "We work with e-commerce brands, hospitality and travel businesses, real estate developers and agencies, and professional services firms (lawyers, accountants, consultancies). Most of our clients are Moroccan or MENA-based, but our approach works for any brand targeting the region.",
    followUps: ["Do you work with startups?", "Do you work outside Morocco?"],
  },
  {
    id: "process",
    title: "How we work",
    category: "process",
    tags: ["process", "how", "work", "method", "steps"],
    keywords: ["process", "how", "work", "method", "approach", "steps", "onboard", "kickoff", "start"],
    answer:
      "Every engagement follows the same four-step rhythm: 1) Discovery and audit, 2) Strategy and roadmap, 3) Execution with weekly sprints, 4) Measurement and iteration. You get a dedicated point of contact, a shared workspace, and clear reporting from day one.",
    followUps: ["How long does onboarding take?", "What does reporting look like?"],
  },
  {
    id: "pricing",
    title: "Pricing and engagement models",
    category: "commercial",
    tags: ["price", "pricing", "cost", "budget", "retainer", "package"],
    keywords: [
      "price",
      "pricing",
      "cost",
      "budget",
      "retainer",
      "package",
      "fees",
      "how",
      "much",
      "expensive",
      "cheap",
      "quote",
    ],
    answer:
      "Every brand is different, so we don't publish a price list. Most engagements are monthly retainers scoped to your goals, channel mix, and creative volume. After a short discovery call, we send a clear proposal with deliverables, timelines, and pricing — no surprises.",
    followUps: ["How do I request a proposal?", "Do you do project-based work?"],
  },
  {
    id: "timeline",
    title: "Timelines and time to results",
    category: "commercial",
    tags: ["timeline", "time", "results", "duration", "long"],
    keywords: [
      "timeline",
      "time",
      "results",
      "long",
      "duration",
      "when",
      "expect",
      "see",
      "roi",
      "fast",
      "quick",
    ],
    answer:
      "Paid campaigns can show results in days, but real, compounding growth usually takes 2-3 months. SEO is a 4-9 month game. A full strategy-to-execution engagement typically runs 3 to 6 months. We will always be honest about what is realistic for your stage and budget.",
    followUps: ["How fast can paid ads work?", "What about SEO?"],
  },
  {
    id: "getting-started",
    title: "Getting started",
    category: "process",
    tags: ["start", "begin", "contact", "onboard", "first", "step"],
    keywords: ["start", "begin", "contact", "onboard", "first", "step", "how", "reach", "call"],
    answer:
      "Easiest path: fill out the contact form or send us a message right here. We usually reply within 24 hours with a few questions and a link to book a free 30-minute discovery call. No pressure, no hard sell.",
    followUps: ["Where can I reach you?", "Do you do free audits?"],
  },
  {
    id: "contact",
    title: "Contact and languages",
    category: "support",
    tags: ["contact", "email", "phone", "language", "english", "french", "arabic"],
    keywords: [
      "contact",
      "email",
      "phone",
      "call",
      "reach",
      "whatsapp",
      "language",
      "english",
      "french",
      "arabic",
      "darija",
    ],
    answer:
      "You can reach us at hello@maroc360.agency, through the contact form, or on LinkedIn. We work in English, French, and Arabic (including Darija), and we are based in Morocco (GMT+1).",
    followUps: ["What are your office hours?", "Do you have a phone number?"],
  },
  {
    id: "careers",
    title: "Careers and joining the team",
    category: "company",
    tags: ["careers", "jobs", "hiring", "team", "join", "apply"],
    keywords: ["careers", "jobs", "hiring", "team", "join", "apply", "work", "with", "us"],
    answer:
      "We are always interested in talented marketers, designers, and developers who care about craft. Check the Careers page for open roles, or send us a short note with what you do best. We hire for attitude and growth, not just CVs.",
    followUps: ["What roles are open?", "Do you take internships?"],
  },
  {
    id: "manifesto",
    title: "Our manifesto and beliefs",
    category: "company",
    tags: ["manifesto", "beliefs", "values", "mission", "why"],
    keywords: ["manifesto", "beliefs", "values", "mission", "why", "purpose", "philosophy"],
    answer:
      "We believe great partnerships build great brands, that marketing is a craft (not guesswork), and that when Moroccan brands win, we all win. We started Maroc 360 to help local businesses build modern brands they are proud of.",
    followUps: ["Read the full manifesto", "What makes you different?"],
  },
  {
    id: "privacy",
    title: "Privacy and data",
    category: "support",
    tags: ["privacy", "data", "gdpr", "cookies"],
    keywords: ["privacy", "data", "gdpr", "cookies", "personal", "information", "policy"],
    answer:
      "We take your privacy seriously. We only collect what we need to deliver our services and reply to your messages, and we never sell your data. The full policy is on our Privacy page.",
    followUps: ["Read the Privacy Policy", "How do I delete my data?"],
  },
  {
    id: "differentiation",
    title: "What makes us different",
    category: "company",
    tags: ["different", "why", "choose", "unique", "better"],
    keywords: ["different", "why", "choose", "unique", "better", "versus", "competitor", "compare"],
    answer:
      "We sit at the intersection of brand and performance. We treat marketing as a craft — research, creative, and data — not as a spend line. We build tools so you can see your numbers clearly, and we are not afraid to tell you when an idea is not going to work.",
    followUps: ["Show me case studies", "What results have you delivered?"],
  },
];

export const defaultSuggestions = [
  "What services do you offer?",
  "How much does it cost?",
  "How do I get started?",
  "Do you work with e-commerce brands?",
  "How long until I see results?",
  "What languages do you work in?",
];
